version: "3"
services:
  service-a:
    container_name: service-a
    build:
      context: ./src/service-a
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src/service-a/:/server
    networks:
      - server

  service-b:
    container_name: service-b
    build:
      context: ./src/service-b
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    volumes:
      - ./src/service-b/:/server
    networks:
      - server

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"
    networks:
      - server

networks: 
  server:
    driver: bridge