basePath: /
info:
  contact:
    email: boscardinvinicius@gmail.com
    name: Vinícius Boscardin
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Desafio Sistema de Temperatura por Cep Go Expert API Docs
  version: 1.0.0
paths: {}
swagger: "2.0"
